### PR TITLE
Add and configure sentry

### PR DESCRIPTION
**Pull request by steventux**
### Context

We would like to see Sentry errors for this application
https://trello.com/c/jeJNy3wr/955-set-up-sentry

### Changes proposed in this pull request

Adds sentry-rails and basic config for Sentry.

### Checklist

- [x] Attach to Trello card
- [x] Rebased main
- [x] Cleaned commit history
- [ ] Tested by running locally

### CODE REVIEW

**Comment by vassyz** [comment]
Does it not need a `SENTRY_DSN` value in Terraform envs?

**Comment by steventux** [comment]
@vassyz I don't see `SENTRY_DSN` in find-a-lost-trn or apply-for-qualified-teacher-status terraform dirs, in fact no mention of Sentry.

**Comment by vassyz** [comment]
@steventux Did some digging as I knew Sentry needs that value to run. It seems it was removed from find-a-lost-trn, but this commit message explains why. https://github.com/DFE-Digital/find-a-lost-trn/commit/d3980e94127c026653e430fa7cc9f0f78ee12974 I didn't know how these env values get set. Approved 👍

**Review by vassyz — APPROVED** [review]

**Comment by steventux** [comment]
@vassyz thanks for info/explanation - I was just crudely searching for `sentry` in these repos to get the basic setup, will add `SENTRY_DSN` to dev secrets if not present before merging.

**Comment by steventux** [comment]
@tvararu I don't have permissions in Sentry to add a new project - I assume the `SENTRY_DSN` keyvault var needs to be unique per-project. Can you add this please?

**Pull request merged**
